apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mgmt-api-deploy
  labels:
    name: book-mgmt-api-deploy
    app: book-management
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: book-mgmt-api-pod
      app: book-management
  template:
    metadata:
      name: book-mgmt-api-pod
      labels:
        name: book-mgmt-api-pod
        app: book-management
    spec:
      containers:
        - name: book-management-api-image
          image: niranjang2/book-management-api:DOCKER_IMG_TAG
          imagePullPolicy: Always
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password
          envFrom:
            - configMapRef:
                name: database-config
          ports:
            - containerPort: 5000
